name: Test Multiple Versions

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: yarn
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files

      - name: Test Default
        run: yarn test:ci

      - name: Test Minimum:
        run: yarn add react@16.8.0 react-dom@16.8.0
        run: yarn test:ci

      - name: Test Stable
        run: yarn add react@17.0.2 react-dom@17.0.2
        run: yarn test:ci

      - name: Test Alpha
        run: yarn add react@18.0.0-alpha-05726d72c-20210927 react-dom@18.0.0-alpha-05726d72c-20210927
        run: yarn test:ci

      - name: Test Experimental
        run: yarn add react@0.0.0-experimental-05726d72c-20210927 react-dom@0.0.0-experimental-05726d72c-20210927
        run: yarn test:ci
